version: '3.8'

services:
  local-ai-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CACHE_TYPE=redis
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./data/logs:/app/data/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: local-ai-agent-network
