version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./workspace:/app/workspace
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - WORKSPACE_DIR=/app/workspace
      - DATABASE_URL=sqlite:///./app.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0

  db:
    image: alpine:latest
    command: tail -f /dev/null
    volumes:
      - ./data:/data

volumes:
  node_modules:
  data:
